---
default_roles:
  - system
#  - alacritty
# - awww
  - bash
  - bat
  - btop
  - delta
#  - duf
  - dust
  - dysk
  - eza
#  - fastfetch
  - fd
#  - fonts
  - fzf
#  - ghostty
  - git
#  - gitui
#  - hyprland
#  - lazydocker
#  - lazygit
  - micro
#  - nano
  - ncdu
#  - neofetch
  - neovim
#  - niri
#  - oxker
#  - procs
  - ripgrep
#  - rofi
  - ssh
  - starship
  - tldr
#  - tmux
#  - waybar
#  - wofi
  - zellij
  - zoxide
  - zsh

git_user_name: "gntsldr"
git_user_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34326566343939383865356265396464623934383538616535333534396137353738663638313131
          3733363739386133326665316437613162393932376332620a626131393861313663323539383432
          30313935386165363963333135663965393538393261393164376431343465323264393366346338
          3235383133306533660a656262356365393161336233376232343730303030633239343663633266
          32386430313465613633386333363661353739343863383830316234616266363863

gitlab_personal_access_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63376132656539393631393636376131316136323831646364363561366336366131643065656239
          3733396165363438643762393030313166626235393861380a346463346339373166616236376161
          63653137383034373361376535393733303833363430656632646236303335363462623437393333
          3562636239366337360a353135633131393032356261303533336133333935636466343333363831
          33393337356366326333623134633538623462616636303330643737626364343463

ssh_key:
  authorized_keys: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            64363662316338353864643764653031616634656366663031633038363732333866313935626362
            6464383666363136626261323961666330353137623535320a386138336239363032363662333062
            31383534386630653332326631363665333031656462353265396262383865663264633435613639
            6464646537663562300a323762363338363336336436336165323131383865306331353263323838
            36623737396631643163376539383063653161396564383361626362366233343834366462356664
            32343631613132323237383033383366336162366165383164653631646432323938643238386566
            34363765663538633533636635643534396663393763376533666661313966643932616237656162
            35363339633135623438643034346133666430313161646264633331383637663038626463653966
            37326365396431386162393935303863343339373963633133666537326363663861313530653235
            36393866613434303465643037343962393031303264323162373162356531326533633463313836
            32326134653636323761393130343439343436306535626134616566623133366633386662613162
            63353164636338623539343835353232333336666534636334313665653430336238633239326338
            66313038333135363635396638343537353638363135663431346131663930613364343134336239
            66303538376532326462343439383334663662366539373538633932613165353437633933616439
            37633434656532353436376163613938313264623134383564333265326539346636323832323539
            33313862653566643961663631623231386663336233343637343531643934366636353030363232
            32356439303637333161323333616339633033373361363136663362353136333563663336376131
            35653533353531393265626134626561373463303065326230626434396138353033636639653162
            65363166303332623261306439666134373762313339663330616361323737613034393237646563
            38383963656333316339363364336330643233616631386462383631643234633265636433316662
            65666630393131383636333833326633396133313334373936313263346465613636646233343161
            36386235636437323935643736663365663764626639643962666433383030396234343235633064
            33663363663832333165653639393964383430396664653832383633373366313736353261656335
            65336134623866376465
  config: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62646436336234663631386436313531613065366166376237313462343761366239653830336266
          6463373365343364613764616639626164326130363462320a353835323637663734326665383034
          32363465393637613563393363373664663139366436333330313163303164336665366534663137
          3863366364656633660a333462346236636134656539663865333864333537626137306461623233
          63306566663461336238333438366566663765663763353465656663623231376533383664306131
          63363434326231383166356362623239643134653433323861366539353261633937313630376663
          30393231306164626466656466613130316563356134396361363362313733646336653264333263
          31363265326430316161643535343831353764616662613233663862303330376534663761643531
          64666336393063383634643763383564616165383064323830663831306137636234386334623365
          62663234653534313838663536636364396365633862333932613136336135656534666335363636
          35316638653030396132663064353265356330343963386166633864326165336632643234646235
          61626262356465633165383365383263313534613566616263393430663230376337663635323661
          39326363356461623730373737633563316562313565373664386430646236663263373361666135
          66353032653131643465393133393763633261616666396565643964353035333466313262323663
          38306134323562396461313930373232306230663731316334626632653833343861323437303435
          65366333646438313264623363653633323563393734393634343631613336616538656630646631
          34363466643036383538623238626563663435386561343533363331333632626332386166363033
          66656436353033663864363065666463643165616131316464393338336562393466316266346563
          64663964393939626535393863326430313337646233333662656331663338666637373062633362
          30343366623933393665346632363937663630343964633932383664616664666637626261333535
          65343733626330643235643463646131353336633664323838356639336566316538383461346133
          66353230633535373535393238643037613131623563366266393065396339656430633031343835
          33663533643564616363373431313433323736396239653266336532663036306632653932366537
          39616637626666336336623561336436663031326562386165386636396564636563343036373936
          37646337323932326132363066623837616462376432386562376539356430363862613134666162
          66386632386538636530303738333861363538626666393038323232623938653464613934643934
          62396439666235306233623634373430303464363261633935363338326261613463623962333833
          36633434623063353939356366353766396562323566666166363130383635393861373134666161
          31386264313838663961633831383062303831363962383462363938356235653531663635626163
          39323763386234396431313934333137333637326366326330653733376133623435636265373636
          61393765353231363436366633366161613131656633343638383561646266343164386266333965
          64353738313938393261343834323264616130653533343663613434646136383363306365333862
          39373432626331363638313931626239646536666337336134326264313165623763333039633566
          62333838613039643666643530636161343332636664336435633532646463626132636366336535
          31643737666235306332336532326134396433386239353639663165623363333533666264626462
          63366138363039373266326264326233656237386638306363386130383766373133373461633232
          34623437353462383534323333346432386431626434313662366231653338383130393035663238
          35383232373430393161373930353433653164366331633834353865656533613034316630653866
          64393533353233326634633038303930383362346233643435313735366565326563626362666563
          35376636623232376530633330353033636264346533383864373064313362343338626433316463
          62346337353333393466343635646235666431613230643731313362343462353633393038663133
          30366636396433313631316530323966323932623763643431386439336564613437303666613434
          33626364356138303334613462396135643834333164366533306634303762656662663764386463
          33333434336662666139343133666232633166633232316234323566303837656664336430366433
          61636438343733643062633239663532336631663961383831393466653332623462666637343330
          34346135616562356262326633643738306362636365616439373765366134666463643833323461
          30323037383037343533343763306439643332653337353166303631353361303836373638393637
          37623931346565643839636130653161366433366662366136393937346261633431666663663435
          30323533353937626564313265333963653034363237653533343336663235326636613739636634
          34623361383631323663666238386666656631646434356132343535643265313564633134343530
          31326438376132303131383539376237376636646233643537373637306162646432663939306462
          33313761626238323064666535343931643734366565313264346361383431313830633563363435
          36376536643565376461303630623866633538386533373262353330316339636334343563383564
          34306539313562336137313337653137663436633832396366646664376365386362656334616537
          63306532333039333566366433323930666266336462613332353432656566363161373035663939
          38366364383433646665306539393066653735656631393465383466373566313438636165613730
          61643233623463383433393139303633383233333531653662353438663964356235363930616461
          63366431313038616534613265656133643435313232383061663163383764313634343037396333
          32376532356231343135343930326363646566623461333538323232653331646431343831336164
          30323866613261326263303233346432393037636166336630386438613037373933313938316662
          31633266353036316533383230393737396566653532613534313535333661373662636232373466
          3161313964383039353737333864636339616231356536343164
