---
- name: awww | Checking for distribution config | {{ ansible_facts.distribution }}
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yml"
  register: awww_distribution_config

- name: awww | Run tasks | {{ ansible_facts.distribution }}
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution }}.yml"
  when: awww_distribution_config.stat.exists
