---
- name: niri | Checking for distribution config | {{ ansible_facts.distribution }}
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yml"
  register: niri_distribution_config

- name: niri | Run tasks | {{ ansible_facts.distribution }}
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution }}.yml"
  when: niri_distribution_config.stat.exists

- name: niri | Copy config
  ansible.builtin.copy:
    src: "{{ role_path }}/files/niri"
    dest: "{{ ansible_facts.user_dir }}/.config/"
    mode: '644'
    directory_mode: '755'
