---
- name: Fish | Checking for Distribution Config | {{ ansible_facts.distribution }}
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yml"
  register: fish_distribution_config

- name: Fish | Run Tasks | {{ ansible_facts.distribution }}
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution }}.yml"
  when: fish_distribution_config.stat.exists

- name: Fish | Set default shell
  ansible.builtin.user:
    name: "{{ ansible_facts.env['USER'] }}"
    shell: /bin/fish
  become: true

- name: Fish | Copy config
  ansible.builtin.copy:
    src: "{{ role_path }}/files/fish"
    dest: "{{ ansible_facts.user_dir }}/.config/"
    mode: '644'
    directory_mode: '755'
