---
- name: Hyprland | Install | {{ ansible_facts.distribution }}
  community.general.pacman:
    name:
      - hyprland
      - hyprland-devel
      - hypridle
      - hyprlock
      - hyprpicker
      - hyprpolkitagent
    state: present
  become: true
