---
- name: Hyprland | Install | {{ ansible_facts.distribution }}
  community.general.pacman:
    name:
      - hyprland
      - hypridle
      - hyprlock
      - hyprpicker
      - hyprpolkitagent
      - hyprshutdown
      - xdg-desktop-portal-hyprland
    state: present
  become: true
