---
- name: Hyprland | Enable Hyprland COPR repository | {{ ansible_distribution }}
  community.general.copr:
    name: solopasha/hyprland
    state: enabled
  become: true

- name: Hyprland | Install | {{ ansible_distribution }}
  ansible.builtin.dnf:
    name:
      - hyprland
    state: present
  become: true
