---
- name: Hyprland | Enable Hyprland COPR repository | {{ ansible_facts.distribution }}
  community.general.copr:
    name: solopasha/hyprland
    state: enabled
  become: true

- name: Hyprland | Install | {{ ansible_facts.distribution }}
  ansible.builtin.dnf:
    name:
      - hyprland
      - hyprland-devel
      - hypridle
      - hyprlock
      - hyprpicker
    state: present
  become: true
