---
- name: Hyprland | Checking for distribution config | {{ ansible_facts.distribution }}
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yml"
  register: hyprland_distribution_config

- name: Hyprland | Run tasks | {{ ansible_facts.distribution }}
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: hyprland_distribution_config.stat.exists

- name: Hyprland | Copy config
  ansible.builtin.copy:
    src: "{{ role_path }}/files/hypr"
    dest: "{{ ansible_facts.user_dir }}/.config/"
    mode: '644'
    directory_mode: '755'
