---
- name: swww | Checking for distribution config | {{ ansible_facts.distribution }}
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yml"
  register: swww_distribution_config

- name: swww | Run tasks | {{ ansible_facts.distribution }}
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution }}.yml"
  when: swww_distribution_config.stat.exists
