---
- name: SSH | Copy authorized keys and config
  ansible.builtin.copy:
    dest: "{{ ansible_facts.user_dir }}/.ssh/{{ ssh_key_item.key }}"
    content: "{{ ssh_key_item.value }}"
    mode: '600'
  no_log: true
  loop_control:
    loop_var: ssh_key_item
  with_items: "{{ ssh_key | default({}) | dict2items }}"
