---
- name: zoxide | Download installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh
    dest: /tmp/zoxide.sh
    mode: '755'

- name: zoxide | Execute installer
  ansible.builtin.command: sh /tmp/zoxide.sh
  args:
    creates: ~/.local/bin/zoxide

- name: zoxide | Remove installer
  ansible.builtin.file:
    path: /tmp/zoxide.sh
    state: absent
