---
- name: Zsh | Install | {{ ansible_facts.distribution }}
  ansible.builtin.dnf:
    name:
      - zsh
    state: present
  become: true

- name: Zsh | Ensures zsh-autosuggestions directory exists | {{ ansible_facts.distribution }}
  ansible.builtin.file:
    path: /usr/share/zsh-autosuggestions/
    state: directory
    mode: '755'
  become: true

- name: Zsh | Install zsh-autosuggestions | {{ ansible_facts.distribution }}
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/zsh-users/zsh-autosuggestions/master/zsh-autosuggestions.zsh
    dest: /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    mode: '644'
  become: true

- name: Zsh | Ensures zsh-syntax-highlighting directory exists | {{ ansible_facts.distribution }}
  ansible.builtin.file:
    path: /usr/share/zsh-syntax-highlighting/
    state: directory
    mode: '755'
  become: true

- name: Zsh | Install zsh-syntax-highlighting | {{ ansible_facts.distribution }}
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/zsh-users/zsh-syntax-highlighting/master/zsh-syntax-highlighting.zsh
    dest: /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    mode: '644'
  become: true
