import = [ "~/.config/alacritty/themes/onedarkpro_onedark.toml" ]

[font]
size = 11.25
normal = { family = "RobotoMono Nerd Font", style = "Medium" }
bold = { family = "RobotoMono Nerd Font", style = "Bold" }
italic = { family = "RobotoMono Nerd Font", style = "Italic" }
bold_italic = { family = "RobotoMono Nerd Font", style = "Bold Italic" }

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
opacity = 0.8
