---
- name: Waybar | Checking for Distribution Config | {{ ansible_facts.distribution }}
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yml"
  register: tmux_distribution_config

- name: Waybar | Run Tasks | {{ ansible_facts.distribution }}
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution }}.yml"
  when: tmux_distribution_config.stat.exists

- name: "Waybar | Copy Waybar config"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/waybar"
    dest: "{{ ansible_facts.user_dir }}/.config/"
    mode: '644'
    directory_mode: '755'
