---
- name: Fastfetch | Download latest version JSON
  ansible.builtin.uri:
    url: https://api.github.com/repos/fastfetch-cli/fastfetch/releases/latest
  register: fastfetch_latest_version_json
  changed_when: false

- name: Fastfetch | Registering fastfetch latest release
  ansible.builtin.set_fact:
    fastfetch_latest_release: "{{ fastfetch_latest_version_json.json.tag_name }}"

- name: Fastfetch | Registering fastfetch latest version
  ansible.builtin.set_fact:
    fastfetch_latest_version: "{{ fastfetch_latest_release.stdout | default('') }}"

- name: Fastfetch | Getting version information
  ansible.builtin.shell:
    cmd: |
      /usr/local/bin/fastfetch --version | cut -d ' ' -f 2
  register: current_fastfetch_version
  changed_when: false
  failed_when: false

- name: Fastfetch | Registering fastfetch Current Version
  ansible.builtin.set_fact:
    fastfetch_current_version: "v{{ current_fastfetch_version.stdout }}"

# - name: "fastfetch | Show current_fastfetch_version debug"
#   ansible.builtin.debug:
#     var: fastfetch_current_version

# - name: "fastfetch | Show fastfetch_latest_release debug"
#   ansible.builtin.debug:
#     var: fastfetch_latest_release

- name: Fastfetch | Install
  when: fastfetch_latest_release not in fastfetch_current_version|default('')
  block:
    - name: Fastfetch | Define fastfetch_file
      ansible.builtin.set_fact:
        fastfetch_file: "fastfetch-linux-amd64"

    - name: Fastfetch | Downloading release
      ansible.builtin.get_url:
        url: https://github.com/fastfetch-cli/fastfetch/releases/download/{{ fastfetch_latest_release }}/{{ fastfetch_file }}.tar.gz
        dest: /tmp/
        mode: '755'

    - name: Fastfetch | Check if a previous installation exists
      ansible.builtin.stat:
        path: /usr/local/bin/fastfetch
      register: fastfetch_binary

    - name: Fastfetch | Remove current installation
      ansible.builtin.file:
        path: /usr/local/bin/fastfetch
        state: absent
      become: true
      when: fastfetch_binary.stat.exists

    - name: Fastfetch | Extract tarball
      ansible.builtin.unarchive:
        src: /tmp/{{ fastfetch_file }}.tar.gz
        dest: /tmp/
        creates: /tmp/{{ fastfetch_file }}
        remote_src: true
      become: true

    - name: Fastfetch | Move binary
      ansible.builtin.copy:
        src: /tmp/{{ fastfetch_file }}/usr/bin/fastfetch
        dest: /usr/local/bin/fastfetch
        mode: '755'
        directory_mode: '755'
        remote_src: true
      become: true

    - name: Fastfetch | Remove tarball
      ansible.builtin.file:
        path: /tmp/{{ fastfetch_file }}.tar.gz
        state: absent
      become: true

    - name: Fastfetch | Remove temp folder
      ansible.builtin.file:
        path: /tmp/{{ fastfetch_file }}
        state: absent
      become: true
