---
- name: Neovim | Uninstall vim | {{ ansible_facts.distribution }}
  ansible.builtin.apt:
    name:
      - vim
      - neovim
    state: absent
  become: true

- name: Neovim | Install dependencies | {{ ansible_facts.distribution }}
  ansible.builtin.apt:
    name:
      - make
      - gcc
      - ripgrep
      - unzip
      - git
    state: present
  become: true
